/*******************************************************************************
 * Default character set: UTF8
 * Server version: 5.0
 * Server version string: WI-V5.0.3.1683 Firebird 5.0
 * Database ODS: 13.1
 * Database page size: 8192
 ******************************************************************************/

/*******************************************************************************
 * Selected metadata objects
 * -------------------------
 * Extracted at 30/08/2025 11:08:16 PM
 ******************************************************************************/

/*******************************************************************************
 * Roles
 * -----
 * Extracted at 30/08/2025 11:08:16 PM
 ******************************************************************************/

/* "PUBLIC" is a system role, no CREATE ROLE statement. */
/* "RDB$ADMIN" is a system role, no CREATE ROLE statement. */
GRANT RDB$ADMIN TO SYSDBA, ABDELDJELIL WITH ADMIN OPTION;
/*******************************************************************************
 * Tables
 * ------
 * Extracted at 30/08/2025 11:08:16 PM
 ******************************************************************************/

CREATE TABLE COFFRE_FORT 
(
  ID                       INTEGER         NOT NULL,
  SOLDE_TOTAL              DECIMAL(15,2) DEFAULT 0 NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE CONTRIBUTIONS 
(
  ID                             INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  PROJET_ID                      INTEGER         NOT NULL,
  PERSONNE_ID                    INTEGER         NOT NULL,
  MONTANT                        DECIMAL(15,2) NOT NULL,
  DATE_CONTRIBUTION                 DATE         DEFAULT CURRENT_DATE,
  PRIMARY KEY (ID)
);
CREATE TABLE DETTES 
(
  ID                              INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  PROJET_ID                       INTEGER         NOT NULL,
  MONTANT                         DECIMAL(15,2) NOT NULL,
  STATUT                          VARCHAR(20) DEFAULT 'EN_COURS',
  DATE_DETTE                         DATE         DEFAULT CURRENT_DATE,
  DATE_REMBOURSEMENT                 DATE,
  PRIMARY KEY (ID)
);
CREATE TABLE PERSONNES 
(
  ID                   INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  NOM                  VARCHAR(100) NOT NULL,
  PRENOM               VARCHAR(100),
  CONTACT              VARCHAR(100),
  PRIMARY KEY (ID)
);
CREATE TABLE PROJETS 
(
  ID                         INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  NOM                        VARCHAR(100) NOT NULL,
  DESCRIPTION                VARCHAR(255),
  DATE_CREATION                 DATE         DEFAULT CURRENT_DATE,
  PRIMARY KEY (ID)
);
CREATE TABLE TRANSACTIONS 
(
  ID                            INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  TYPE_TRANSACTION              VARCHAR(20) NOT NULL,
  MONTANT                       DECIMAL(15,2) NOT NULL,
  PROJET_ID                     INTEGER,
  PERSONNE_ID                   INTEGER,
  DATE_TRANSACTION            TIMESTAMP         DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);
CREATE TABLE VIREMENTS_PROGRAMMES 
(
  ID                             INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  PROJET_ID                      INTEGER         NOT NULL,
  PERSONNE_ID                    INTEGER,
  MONTANT                        DECIMAL(15,2) NOT NULL,
  FREQUENCE                      VARCHAR(20) NOT NULL,
  DATE_DEBUT                        DATE         NOT NULL,
  DATE_FIN                          DATE,
  PROCHAIN_VIREMENT                 DATE         NOT NULL,
  ACTIF                         SMALLINT         DEFAULT 1,
  PRIMARY KEY (ID)
);
SET TERM ^^ ;
