- جدول المستخدمين (العائلة / الأعضاء)
CREATE TABLE personnes (
    personne_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR(100) NOT NULL,
    prenom      VARCHAR(100),
    email       VARCHAR(150),
    telephone   VARCHAR(50)
);

-- جدول المشاريع
CREATE TABLE projets (
    projet_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    date_creation DATE DEFAULT CURRENT_DATE
);

-- جدول المساهمات (إيداع شخص في مشروع)
CREATE TABLE contributions (
    contrib_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personne_id  INTEGER NOT NULL,
    projet_id    INTEGER NOT NULL,
    montant      DECIMAL(15,2) NOT NULL,
    date_contrib DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (personne_id) REFERENCES personnes(personne_id),
    FOREIGN KEY (projet_id) REFERENCES projets(projet_id)
);

-- جدول الصندوق المركزي (Coffre-fort)
CREATE TABLE coffre_fort (
    mouvement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_mouv    VARCHAR(20) NOT NULL, -- DEPOT / RETRAIT / VIREMENT
    montant      DECIMAL(15,2) NOT NULL,
    date_mouv    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reference    VARCHAR(200)
);

-- جدول القروض (الاستدانة من الصندوق)
CREATE TABLE dettes (
    dette_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projet_id    INTEGER NOT NULL,
    montant      DECIMAL(15,2) NOT NULL,
    date_dette   DATE DEFAULT CURRENT_DATE,
    statut       VARCHAR(20) DEFAULT 'EN_COURS', -- EN_COURS / REMBOURSEE
    FOREIGN KEY (projet_id) REFERENCES projets(projet_id)
);

-- جدول التحويلات المبرمجة (Scheduled transfers)
CREATE TABLE virements_programmes (
    virement_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projet_id    INTEGER NOT NULL,
    montant      DECIMAL(15,2) NOT NULL,
    frequence    VARCHAR(20) NOT NULL, -- JOURNALIER / HEBDO / MENSUEL
    prochaine_date DATE NOT NULL,
    statut       VARCHAR(20) DEFAULT 'ACTIF', -- ACTIF / SUSPENDU / TERMINE
    FOREIGN KEY (projet_id) REFERENCES projets(projet_id)
);
